name: CI/CD → Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: p2p-web-433803
  GAR_LOCATION: us-central1
  REGION: us-central1
  BACKEND_SERVICE: p2p-web-backend
  FRONTEND_SERVICE: p2p-web-frontend

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP  
        uses: google-github-actions/auth@v2  
        with:  
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}  
          service_account: ${{ vars.WIF_SERVICE_ACCOUNT }} 
      
      - name: Set up Cloud SDK  
        uses: google-github-actions/setup-gcloud@v2  
        with:  
          version: '>= 390.0.0'

      - name: Build & Push Backend  
        run: |
          gcloud builds submit \
            --region=$REGION \
            --tag=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${BACKEND_SERVICE}/${BACKEND_SERVICE}:${{ github.sha }} \
            ./p2p-backend

      - name: Deploy Backend to Cloud Run  
        id: deploy-backend
        uses: google-github-actions/deploy-cloudrun@v2  
        with:  
          service: ${{ env.BACKEND_SERVICE }}  
          region: ${{ env.REGION }}  
          image: ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${BACKEND_SERVICE}/${BACKEND_SERVICE}:${{ github.sha }}

      - name: Build & Push Frontend  
        run: |
          gcloud builds submit \
            --region=$REGION \
            --tag=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${FRONTEND_SERVICE}/${FRONTEND_SERVICE}:${{ github.sha }} \
            ./p2p-frontend 

      - name: Deploy Frontend to Cloud Run  
        id: deploy-frontend
        uses: google-github-actions/deploy-cloudrun@v2  
        with:  
          service: ${{ env.FRONTEND_SERVICE }}  
          region: ${{ env.REGION }}  
          image: ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${FRONTEND_SERVICE}/${FRONTEND_SERVICE}:${{ github.sha }} 

      - name: Show URLs
        run: |
          echo "Backend URL: ${{ steps.deploy-backend.outputs.url }}"  
          echo "Frontend URL: ${{ steps.deploy-frontend.outputs.url }}"  
