name: Build & Deploy → Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: p2p-web-433803
  REGION: us-central1
  GAR_HOST: us-central1-docker.pkg.dev

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: p2p-backend
            repo: p2p-web-backend/p2p-web-backend
            service: p2p-web-backend
          - dir: p2p-frontend
            repo: p2p-web-frontend/p2p-web-frontend
            service: p2p-web-frontend

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account:            ${{ vars.WIF_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # Build & push image via Cloud Build
      - name: Build & push ${{ matrix.service }}
        run: |
          IMAGE="${{ env.GAR_HOST }}/${{ env.PROJECT_ID }}/${{ matrix.repo }}:${{ github.sha }}"
          gcloud builds submit ${{ matrix.dir }} \
            --region=${{ env.REGION }} \
            --tag="$IMAGE"
            --suppress-logs

      # Deploy to Cloud Run
      - uses: google-github-actions/deploy-cloudrun@v2.7.4
        id: deploy
        with:
          service: ${{ matrix.service }}
          region:  ${{ env.REGION }}
          image:   ${{ env.GAR_HOST }}/${{ env.PROJECT_ID }}/${{ matrix.repo }}:${{ github.sha }}
          flags:   "--revision-suffix=${{ github.run_id }} --allow-unauthenticated"

      - name: Publish URL
        run: echo "${{ matrix.service }} → ${{ steps.deploy.outputs.url }}" >> $GITHUB_STEP_SUMMARY
