name: Deploy to Cloud Run

on:            # run only when commits land on main, plus manual trigger
  push: { branches: [ main ] }
  workflow_dispatch:

env:
  PROJECT_ID: p2p-web-433803
  REGION:     us-central1
  GAR:        us-central1-docker.pkg.dev     # Artifact Registry hostname

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }   # OIDC → GCP

    steps:
    - uses: actions/checkout@v4     # lightweight checkout :contentReference[oaicite:0]{index=0}

    - id: auth                      # OIDC, no long‑lived JSON key needed
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.WIF_PROVIDER }}
        service_account:            ${{ vars.WIF_SERVICE_ACCOUNT }}
        token_format:               'access_token'      :contentReference[oaicite:1]{index=1}

    - uses: docker/login-action@v3  # push to Artifact Registry
      with:
        registry:  ${{ env.GAR }}
        username:  oauth2accesstoken
        password:  ${{ steps.auth.outputs.access_token }}

    # --- backend ---
    - run: |
        docker build -t "$GAR/${{ env.PROJECT_ID }}/p2p-web-backend/app:${{ github.sha }}" ./p2p-backend
        docker push  "$GAR/${{ env.PROJECT_ID }}/p2p-web-backend/app:${{ github.sha }}"

    - uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: p2p-web-backend
        region:  ${{ env.REGION }}
        image:   $GAR/${{ env.PROJECT_ID }}/p2p-web-backend/app:${{ github.sha }}
      id: backend                            :contentReference[oaicite:2]{index=2}

    # --- frontend ---
    - run: |
        docker build \
          --build-arg REACT_APP_API_URI="${{ secrets.REACT_APP_API_URI }}" \
          --build-arg REACT_APP_EMAIL_JS_SERVICE_ID="${{ secrets.REACT_APP_EMAIL_JS_SERVICE_ID }}" \
          --build-arg REACT_APP_EMAIL_JS_TEMPLATE_ID="${{ secrets.REACT_APP_EMAIL_JS_TEMPLATE_ID }}" \
          --build-arg REACT_APP_EMAILJS_PUBLIC_KEY="${{ secrets.REACT_APP_EMAILJS_PUBLIC_KEY }}" \
          -t "$GAR/${{ env.PROJECT_ID }}/p2p-web-frontend/app:${{ github.sha }}" ./p2p-frontend
        docker push "$GAR/${{ env.PROJECT_ID }}/p2p-web-frontend/app:${{ github.sha }}"

    - uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: p2p-web-frontend
        region:  ${{ env.REGION }}
        image:   $GAR/${{ env.PROJECT_ID }}/p2p-web-frontend/app:${{ github.sha }}
      id: frontend

    - run: |
        echo "🔗 Backend  → ${{ steps.backend.outputs.url }}"
        echo "🔗 Frontend → ${{ steps.frontend.outputs.url }}"
