name: CI/CD → Cloud Run
on: [push]
env:
  PROJECT_ID: p2p-web-433803
  GAR_LOCATION: us-central1
  REGION: us-central1
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account:            ${{ vars.WIF_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true  

      # build + push images ---------------------------------------------------
      - name: Build backend image
        run: |
          gcloud builds submit \
            --region=${{ env.REGION }} \
            --tag=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/p2p-web-backend/p2p-web-backend:${{ github.sha }} \
            p2p-backend

      - name: Build frontend image
        run: |
          gcloud builds submit \
            --region=${{ env.REGION }} \
            --tag=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/p2p-web-frontend/p2p-web-frontend:${{ github.sha }} \
            p2p-frontend

      # deploy ----------------------------------------------------------------
      - uses: google-github-actions/deploy-cloudrun@v2
        id: deploy-backend
        with:
          service: p2p-web-backend
          region:  ${{ env.REGION }}
          image:   ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/p2p-web-backend/p2p-web-backend:${{ github.sha }}

      - uses: google-github-actions/deploy-cloudrun@v2
        id: deploy-frontend
        with:
          service: p2p-web-frontend
          region:  ${{ env.REGION }}
          image:   ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/p2p-web-frontend/p2p-web-frontend:${{ github.sha }}

      - run: |
          echo "Backend URL : ${{ steps.deploy-backend.outputs.url }}"
          echo "Frontend URL: ${{ steps.deploy-frontend.outputs.url }}"
