# This workflow builds and pushes Docker containers to Google Artifact Registry
# and deploys them on Cloud Run when a commit is pushed to the "main" branch.

name: 'Build and Deploy Frontend and Backend to Cloud Run'

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: 'p2p-web-433803'
  REGION: 'us-central1'
  FRONTEND_SERVICE: 'p2p-web-frontend'
  BACKEND_SERVICE: 'p2p-web-backend'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/426650378682/locations/global/workloadIdentityPools/github/providers/my-repo'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: 'gcr.io'

      # Build and Push Frontend Container (p2p-frontend)
      - name: 'Build and Push Frontend Container'
        run: |-
          DOCKER_TAG="gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_SERVICE }}:${{ github.sha }}"
          docker buildx build --platform linux/amd64 \
            --build-arg REACT_APP_API_URI=${{ secrets.REACT_APP_API_URI }} \
            --build-arg REACT_APP_EMAIL_JS_SERVICE_ID=${{ secrets.REACT_APP_EMAIL_JS_SERVICE_ID }} \
            --build-arg REACT_APP_EMAIL_JS_TEMPLATE_ID=${{ secrets.REACT_APP_EMAIL_JS_TEMPLATE_ID }} \
            --build-arg REACT_APP_EMAILJS_PUBLIC_KEY=${{ secrets.REACT_APP_EMAILJS_PUBLIC_KEY }} \
            --build-arg REACT_APP_RECAPTCHA_SITE_KEY=${{ secrets.REACT_APP_RECAPTCHA_SITE_KEY }} \
            --build-arg REACT_APP_RECAPTCHA_SECRET_KEY=${{ secrets.REACT_APP_RECAPTCHA_SECRET_KEY }} \
            --build-arg GENERATE_SOURCEMAP=${{ secrets.GENERATE_SOURCEMAP }} \
            -t "${DOCKER_TAG}" \
            --file ./p2p-frontend/Dockerfile --push ./p2p-frontend

      # Deploy Frontend to Cloud Run
      - id: deploy_frontend
        name: 'Deploy Frontend to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.FRONTEND_SERVICE }}'
          region: '${{ env.REGION }}'
          image: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_SERVICE }}:${{ github.sha }}'

      # Build and Push Backend Container (p2p-backend)
      - name: 'Build and Push Backend Container'
        run: |-
          DOCKER_TAG="gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:${{ github.sha }}"
          docker buildx build --platform linux/amd64 -t "${DOCKER_TAG}" --file ./p2p-backend/Dockerfile --push ./p2p-backend

      # Deploy Backend to Cloud Run
      - id: deploy_backend
        name: 'Deploy Backend to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.BACKEND_SERVICE }}'
          region: '${{ env.REGION }}'
          image: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:${{ github.sha }}'

      - name: 'Show Frontend Output'
        run: |
          echo "Frontend URL: \${{ steps.deploy_frontend.outputs.url }}"

      - name: 'Show Backend Output'
        run: |
          echo "Backend URL: \${{ steps.deploy_backend.outputs.url }}"
